{% set version = "1.0.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rsvd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rsvd_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rsvd/rsvd_{{ version }}.tar.gz
  sha256: e40686b869acd4f71fdb1e8e7a6c64cd6792fc9d52a78f9e559a7176ab84e21e

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base >=4.0.0
    - r-matrix
  run:
    - r-base >=4.0.0
    - r-matrix

test:
  commands:
    - $R -e "library('rsvd')"           # [not win]
    - "\"%R%\" -e \"library('rsvd')\""  # [win]

about:
  home: https://github.com/erichson/rSVD
  license: GPL-3.0-or-later
  summary: 'Low-rank matrix decompositions are fundamental tools and widely used for data analysis, dimension reduction, and data compression. Classically, highly accurate  deterministic matrix algorithms are used for this task. However, the emergence of  large-scale data has severely challenged our computational ability
    to analyze big data.  The concept of randomness has been demonstrated as an effective strategy to quickly produce approximate answers to familiar problems such as the singular value decomposition (SVD).  The rsvd package provides several randomized matrix algorithms such as the randomized  singular value decomposition
    (rsvd), randomized principal component analysis (rpca),  randomized robust principal component analysis (rrpca), randomized interpolative  decomposition (rid), and the randomized CUR decomposition (rcur). In addition several plot  functions are provided. The methods are discussed in detail by Erichson et al. (2016) <arXiv:1608.02148>. '
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rsvd
# Type: Package
# Title: Randomized Singular Value Decomposition
# Version: 1.0.0
# Date: 2018-11-05
# Authors@R: c(person("N. Benjamin", "Erichson", role = c("aut", "cre"), email = "erichson@uw.edu"))
# Author: N. Benjamin Erichson [aut, cre]
# Maintainer: N. Benjamin Erichson <erichson@uw.edu>
# Description: Low-rank matrix decompositions are fundamental tools and widely used for data analysis, dimension reduction, and data compression. Classically, highly accurate  deterministic matrix algorithms are used for this task. However, the emergence of  large-scale data has severely challenged our computational ability to analyze big data.  The concept of randomness has been demonstrated as an effective strategy to quickly produce approximate answers to familiar problems such as the singular value decomposition (SVD).  The rsvd package provides several randomized matrix algorithms such as the randomized  singular value decomposition (rsvd), randomized principal component analysis (rpca),  randomized robust principal component analysis (rrpca), randomized interpolative  decomposition (rid), and the randomized CUR decomposition (rcur). In addition several plot  functions are provided. The methods are discussed in detail by Erichson et al. (2016) <arXiv:1608.02148>.
# Depends: R (>= 3.2.2)
# Imports: Matrix
# License: GPL (>= 3)
# LazyData: TRUE
# URL: https://github.com/erichson/rSVD
# BugReports: https://github.com/erichson/rSVD/issues
# Suggests: ggplot2, testthat
# RoxygenNote: 6.1.0
# NeedsCompilation: no
# Packaged: 2018-11-05 19:35:46 UTC; ben
# Repository: CRAN
# Date/Publication: 2018-11-06 06:00:03 UTC
