travis:
  secure:
    BINSTAR_TOKEN: QGvF8iRYaykraw33zR0zbz7zw0IAHGiuRDJgkb84sQascS07ISLsQFjxINIy6q8BDPkvP8cZgmvvKaXuTJFpViryeDjx0+ZL9SK9ywaOA0zA55WnWxXLtv4hTpE+QGiptNshsdixEgI+8bpxz21PIUCkomUsHDoE1qtGxWC7kGVlWbl9eEmHuzdqesugJ3M4dAiZsS9wyaGIyeUMOynkACRAY9C5+uL8W3qZdo51c8l8mTuH7NgIETRyKMOjUoXpumf1dumuya28mGOsJoeXWZVvHvbzTbNS2Igh5Rk8WPBiPMAtElSBOeN69XXs7JDp6V6IjtyaZwsUMPjO/Xvp3JT0kEt3BZ39HxFrHpgek6LuOr9twDQgIt/IyCK7AkIKBJ48xeWVSfNMTmq56Bz1yCCZYqLlXU82Z5XVXNO6V4mI25sTxS0DtR6QGYJVa08qMN4cMbLU58WMa6AUtX3/HYQCR5nxCY8bBObTuajpvVngw4+jvTRfSiT352cEBzRMgc2w3lFAIlUrl7y8oe0dd6zKrsq8v+c1g7AjsBhdQCr86K7zpqyx6n8BIwJbgJ5zlWjHUA/LfyynhWvkThc/GdVVo9elb+EOhI9CoPqXv1iEsrdePEL8uWVw0dGelHPqz1XBaYlOlPT7QVh/q3EblSFeQcXWHDdsNzCq913xts8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
