appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: WeL6khC3XfGCvnLvEzk9rMWjSJ47803hS14j3krsIMBjOhchGybCWPWHJv7BxhQsapqiVLiiVb2kU6rJXNTzgkxNZ1yBhxAsf8N0BWPlf4tkIGtZpi89bQHy6A7sGT3h/ziSReZFjcMS0PwjtM9scfBYR1U5HVrXjdzqBzRs+w7xM78zeegugFdBD5SjVztGk7/Epg7PEYfPXUWKbYnenwwVJ6ezcgWXzKfX966EQI+0DPNsLSr6d0F06RmZHMzIqcRC80XujtsFJ6t+/qTJUkGtPduWVjlM1X6mqKqDY33G1QwYhvHLxxoMn9m6tS2jz33VEpn4emNLh/o8c2LJDgxOulvT7+tMQ+50VPnjFk56nVmHsaSG/QN+PzK+OMUKxNkmsjDWCZAQxIGHyUiwdya1ZQbwpj8XUmSjLPEj5u4giixZU4vF0aabl76zhFKAflY0pYxhVIXxiMi4sPPwE21+eDUjDKiTm7c09nz+Mnd9SFWQmMHAPUWXZgmbm6eVCNXtHYjBatpEBIn1PUUiLhqxsdwj7bBUyYJLrmfDztildHZIQRrmI5fEBiuUMpWVA+pA4x/BEUUL8bAq/z9gAw+s6wzGPMFTVau9pQSEvxqiB/zhlU3w93Jp60tcdo4l6pW9TmqcjkT8QotfQBoU16xHwMloV5rpiQWjuYVRDwg=}
bot:
  automerge: true
