travis:
  secure:
    BINSTAR_TOKEN: BOW4E+qyXs2y6Xfw5ETtqinUffVjUDH9GnaXvTv+ZeIUBxBZEkDVDzJCWX3qpm0OOB0rQ6npTgCkZJibhhOYglzlw5B/4lUk6GfaJC5XviWgXaQa4A3gOBHzavGc185CPlaKVjrjs3+HFYDppCXU8P9l3cHa306+JB95xv2g/oEcyNG3Rq1tc2pvl8bqrTzw0e6M58TITTCTqYGgrIOydWXpdcfyO1eFBf+o8vDExuIpe9t9Gk148nFG7Ffb8EHRylJ1/yUGo20HVgar6dGLUG+rgcS2NgrmnWVFvChaWGF8JLWJhpXsazHUNvIyz+iCbR7R7JCA69aoIfau7FqQVw1CGSk56vWUd3PmaaHIWTLHV09rlNS9HxxQNT+kpdZGI8r2ZtrJM42/oFabVkTKfcE9lMBanw/4nuhk5INMJ3k8fUgb6gGYB4KAcOEbs6rHKNRqhpdwkdXXuGVUSBukpNYQ1cVeQCt5VeCx7qvnlPYNABhldaSIqgdD0CBk45Bm++RsM6uL5r8dNzB4g5E7QbwefEpVJGTwbbZZM5b4RjnzVXsXtgS18+Jx5e0eGRkmf7YRRQopLJTifctwoEhJVPiJZLDccPH92gutpcIUNuokmYffK2c32rhaTSSBtlKYy1IBi+y5u0pgRCO6ToF+SlTar8rM6zHHAlHst9hr2pw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
